server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 查询数据
data:
  page-size: 10000

# excel
excel:
  sheet:
    max-size: 1000000

# 异步线程池
async:
  thread:
    core-pool-size: 5
    max-pool-size: 7
    queue-capacity: 10
    keep-alive-seconds: 30
    thread-name-prefix: excel-

# 七牛云文件路径
qiniu:
  access-key: vHq8aLU3wG_yaUcPv8crA6cIuxBPJm412RK7Va1M
  secret-key: BRyDPnTIEUWanXf3xYrFaH1SLeoBlA9M7LpW9Zds
  bucket: million-data
  url: rjyefa9l9.hn-bkt.clouddn.com
  expire-seconds: 3600

# 本地文件路径
file:
  path: E:/java/filePath/
